<a href="https://colab.research.google.com/github/Khiwila/handson-ml/blob/master/Chapter9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf


In [0]:
x = tf.Variable(4, dtype = tf.float32, name = 'x')
y = tf.Variable(3, dtype = tf.float32, name = 'y')
c = tf.constant(2, dtype = tf.float32)


In [0]:
m = y + c
w = x*x*y + y + c
n = m + 4

In [6]:
init = tf.global_variables_initializer()

with tf.Session() as sesion1:
  init.run()
  w1 = w.eval()
  print(n)
  print(w1)
  

Tensor("add_3:0", shape=(), dtype=float32)
53.0


In [0]:
w = tf.constant(3)
x = w + 2 
y = x + 5
z = x * 3


In [8]:
with tf.Session() as sesion2:
  y_eval, z_eval = sesion2.run([y, z])
  print(y_eval, z_eval)


10 15


In [0]:
A = tf.placeholder(tf.float32, shape = (None,3))
B = A + 5


In [10]:
with tf.Session() as sesion3:
  B_val_1 = B.eval(feed_dict = {A:[[3,4,2]]})
  B_val_2 = B.eval(feed_dict = {A:[[3,4,2],[-2,0,5]]})

  
print (B_val_1)
print (B_val_2)

               

[[8. 9. 7.]]
[[ 8.  9.  7.]
 [ 3.  5. 10.]]


In [11]:
# linear regression with tensorflow

import numpy as np
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()
m, n = housing.data.shape
housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]

In [12]:
m,n

(20640, 8)

In [23]:
housing('MedInc')

TypeError: ignored